---
title: "NCAlum EDA"
author: "Mei Maddox"
date: "1/13/2022"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(plotly)
```

```{r include=FALSE}
id <- "1rDlrP_1GTUz6Ttof5QAzSf-LESbKe-Hf"
df <- readr::read_csv(sprintf("https://docs.google.com/uc?id=%s&export=download", id))


df.subset <- df %>%
  filter_at(vars(matches("3")), all_vars(is.na(.))) %>%
  select(matches("DIVISION|ACADEMIC_PROGRAM"),Industry,-matches("3")) %>%
  mutate(Industry=forcats::fct_collapse(Industry,
                                      `Arts and Media`=c("Art","Arts","Antiques","Arts & Entertainment","Online Media","Performing Arts","Communications","Entertainment","Film","Journalism","Media","Music","Photography","Publishing"),
                                      `Health and Medicine`=c("Dentistry","Health & Fitness","Healthcare","Healthcare Services","Medical","Medical Equipment","Medical Research","Medicine","Pharmaceutical","Psychotherapy","Public Health"),
                                      `Government and Social Services`=c("Attorney","City/County/State","Community Services","Defense & Space","Development","Economic Development","Environmental Law","Government","International Relations","Law","Military","Non Profit","Nonprofit","Philanthropy","Public Relations","Religion"),
                                      `Education`=c("Education","Education / Training","Educational Services","Higher education","Library","Museums and Institutions"),
                                      `STEM`=c('Agriculture','Archaeology','Architecture','Computer Software','Construction','Data Science','Electronics','Engineering','Environmental','Environmental Science','Environmental Services','Farming','Imaging','Information Technology','IT Communications','Manufacturing','Marine','Research','Software','Software Design','Technology','Textiles'),
                                      `Business, Finance, and Retail`=c('Accounting','Advertising','Banking','Business','Business Consulting','Consulting','Financial Services','Food','Food and Lodging','Food Franchise','Food Service','Health Care Consulting','Home Improvement','Hospitality','Human Resources','Insurance','International Economic Development Consulting','Investment banking','Investments','Marketing','Non-profit consulting','Pet Food','Real Estate','Restaurant','Retail','Services','Shipping','Sports Management','Transportation'))) %>%
  mutate(Industry=forcats::fct_relevel(Industry, sort(levels(Industry)))) %>%
  mutate(Industry=forcats::fct_lump(Industry,n=13)) 
```

```{r include=FALSE, echo=FALSE}
df.subset %>%
  sapply(function(x){sum(is.na(x))})
```

## Single Major

```{r include=FALSE}
df.single <- df.subset %>%
  filter_at(vars(matches("2")), all_vars(is.na(.))) %>%
  select(DIVISION_1,Industry) %>%
  tidyr::drop_na() %>%
  group_by(Industry) %>%
  count(DIVISION_1) %>%
  mutate(prop=n/sum(n))
```

```{r echo=FALSE}
df.single %>%
  ggplot(aes(x=100*prop, y=Industry, fill=DIVISION_1)) +
  geom_bar(stat='identity', width=0.7) +
  scale_fill_discrete(guide = guide_legend(reverse=TRUE)) + 
  theme_classic() +
  theme(legend.position="top") +
  labs(x="Percent (%)", y="", title="Career Industry by Single-Major Academic Division", subtitle="Based on NC Alumni Data", fill="") +
  scale_x_continuous(expand=expansion(mult=c(0,NA)))

df.single %>%
  ggplot(aes(x=DIVISION_1, y=n, fill=DIVISION_1)) +
  geom_bar(stat='identity', width=0.7) +
  facet_wrap(vars(Industry)) +
  scale_fill_discrete(guide = guide_legend(reverse=TRUE)) + 
  theme(legend.position="top",
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank()) +
  labs(x="", y="Frequency", title="Career Industry by Single-Major Academic Division", subtitle="Based on NC Alumni Data", fill="")
```

## Double Major

```{r include=FALSE}
df.double <- df.subset %>%
  filter_at(vars(matches("2")), any_vars(!is.na(.))) %>%
  select(matches("DIVISION"),Industry) %>%
  tidyr::drop_na() %>%
  group_by(DIVISION_1, DIVISION_2) %>%
  count(Industry) %>%
  mutate(prop=n/sum(n))
```

```{r echo=FALSE}
df.double %>%
  ggplot(aes(x=100*prop, y=DIVISION_2, fill=Industry)) +
  geom_bar(stat='identity', width=0.7,color="black") +
  facet_wrap(vars(DIVISION_1)) +
  theme_classic() +
  #theme(legend.position="top") +
  labs(x="Percent (%)", y="", title="Career Industry by Double-Major Academic Division", subtitle="Based on NC Alumni Data", fill="") +
  scale_x_continuous(expand=expansion(mult=c(0,NA)))
```

## Any-Degree

```{r include=FALSE, eval=FALSE}
#devtools::install_github("mattflor/chorddiag")
df %>% 
  count(DIVISION_1, DIVISION_2) %>%
  tidyr::pivot_wider(names_from=DIVISION_1, values_from=n) %>%
  mutate(DIVISION_2 = tidyr::replace_na(DIVISION_2, "NA")) %>%
  tibble::column_to_rownames(var="DIVISION_2") %>% 
  chorddiag::chorddiag(groupnamePadding = 20)
```
